// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVFZqMWlbtclNMC4iDXcLH0t2xqFxXFho',
    appId: '1:752070888758:web:2e0e90d86d9e1e1df3f797',
    messagingSenderId: '752070888758',
    projectId: 'unifind-d2234',
    authDomain: 'unifind-d2234.firebaseapp.com',
    storageBucket: 'unifind-d2234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz_mXgGq7PJecwbtTGU3eXWpRaV3vTtpo',
    appId: '1:752070888758:android:660845f33450f7f7f3f797',
    messagingSenderId: '752070888758',
    projectId: 'unifind-d2234',
    storageBucket: 'unifind-d2234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMu1RF18tKwoFl7R1iOmDcOyoDKMrTDs',
    appId: '1:752070888758:ios:cbc9d5dd6a68fefcf3f797',
    messagingSenderId: '752070888758',
    projectId: 'unifind-d2234',
    storageBucket: 'unifind-d2234.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMu1RF18tKwoFl7R1iOmDcOyoDKMrTDs',
    appId: '1:752070888758:ios:cbc9d5dd6a68fefcf3f797',
    messagingSenderId: '752070888758',
    projectId: 'unifind-d2234',
    storageBucket: 'unifind-d2234.firebasestorage.app',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVFZqMWlbtclNMC4iDXcLH0t2xqFxXFho',
    appId: '1:752070888758:web:2dad572b30c11847f3f797',
    messagingSenderId: '752070888758',
    projectId: 'unifind-d2234',
    authDomain: 'unifind-d2234.firebaseapp.com',
    storageBucket: 'unifind-d2234.firebasestorage.app',
  );
}
